---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: podinfo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: podinfo
        env:
        - name: PODINFO_UI_COLOR
          value: "#00ff00"
        - name: PODINFO_UI_MESSAGE
          value: "Development Environment"
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
