---
apiVersion: v1
kind: Service
metadata:
  name: go-crud-api
  namespace: go-crud-api
  labels:
    app: go-crud-api
spec:
  type: ClusterIP
  selector:
    app: go-crud-api
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
