---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crud-api
  namespace: go-crud-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: go-crud-api
        env:
        - name: PORT
          value: "8080"
        - name: ENVIRONMENT
          value: "staging"
        resources:
          requests:
            cpu: 75m
            memory: 48Mi
          limits:
            cpu: 150m
            memory: 96Mi
